# Generated by Django 5.0.7 on 2024-07-24 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequel',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
