# Generated by Django 5.0.7 on 2024-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0002_sequel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequel',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequel',
            name='user_popularity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
