# Generated by Django 5.0.7 on 2024-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0004_ratingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='logged_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
