# Generated by Django 5.0.7 on 2024-08-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0005_ratingreview_logged_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='logged_id',
            field=models.IntegerField(blank=True),
        ),
    ]
