# Generated by Django 5.0.7 on 2024-08-24 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0008_searchhistory_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='movie_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
