# Generated by Django 5.0.7 on 2024-08-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0009_watchhistory_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchhistory',
            name='movie_name',
        ),
    ]
