# Generated by Django 5.0.7 on 2024-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_sequels', '0010_remove_watchhistory_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='movie_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
