# Generated by Django 5.0.7 on 2024-08-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_searchhistory_watchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchhistory',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
    ]
